name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Build Binary
        run: |
          VERSION="$(git describe --tags --always | sed 's/^v//')"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%S)
          
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.goarch }} go build -ldflags="-X 'main.buildVersion=${VERSION}' -X 'main.buildCommit=${COMMIT_HASH}' -X 'main.buildDate=${BUILD_DATE}' -s -w" -o build/fping-exporter-linux-${{ matrix.goarch }}

      - name: Compress Binary
        run: |
          upx --best build/fping-exporter-linux-${{ matrix.goarch }}

      - name: Upload Binaries to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/fping-exporter-linux-${{ matrix.goarch }}
          asset_name: fping-exporter-linux-${{ matrix.goarch }}