name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload:
    name: Build, Compress, and Upload Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Build static binary
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o build/fping-exporter-linux-${{ matrix.goarch }}

      - name: Compress binary with UPX
        run: |
          upx --best build/fping-exporter-linux-${{ matrix.goarch }}

      - name: Upload binaries to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/fping-exporter-linux-${{ matrix.goarch }}
          asset_name: fping-exporter-linux-${{ matrix.goarch }}